name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 0 * * *'
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  integration_test:
    name: rs_${{ matrix.ROSETTASCIIO_VERSION }}-hs_${{ matrix.HYPERSPY_VERSION }}-ext_${{ matrix.EXTENSION_VERSION }}${{ matrix.LABEL }}
    strategy:
      fail-fast: false
      matrix:
        EXTENSION_VERSION: ['release', 'dev']
        HYPERSPY_VERSION: ['release', 'RnM', 'RnP']
        ROSETTASCIIO_VERSION: ['release', 'dev']
        NUMBA_DEV: [false]
        DEPENDENCIES_DEV: ['']
        DEPENDENCIES_PRE_RELEASE: ['']
        USE_CONDA: [false]
        include:
          - DEPENDENCIES_DEV: 'matplotlib scipy scikit-image scikit-learn'
            LABEL: -dependencies_dev
            HYPERSPY_VERSION: 'RnM'
            ROSETTASCIIO_VERSION: 'dev'
            EXTENSION_VERSION: 'dev'
          - DEPENDENCIES_PRE_RELEASE: 'matplotlib scipy scikit-learn sympy h5py scikit-image numba'
            LABEL: -dependencies_pre_release
            HYPERSPY_VERSION: 'RnM'
            ROSETTASCIIO_VERSION: 'dev'
            EXTENSION_VERSION: 'dev'
          - NUMBA_DEV: true
            LABEL: -dependencies_numba_dev
            HYPERSPY_VERSION: 'RnM'
            ROSETTASCIIO_VERSION: 'dev'
            EXTENSION_VERSION: 'dev'
          - HYPERSPY_VERSION: 'release'
            ROSETTASCIIO_VERSION: 'release'
            EXTENSION_VERSION: 'release'
            USE_CONDA: true

    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/integration_tests.yml@main
    with:
      # don't run etspy until test suite is fixed
      # EXTENSIONS: 'exspy holospy lumispy pyxem atomap etspy'
      EXTENSIONS: 'exspy holospy lumispy pyxem atomap'
      EXTENSION_VERSION: ${{ matrix.EXTENSION_VERSION }}
      HYPERSPY_VERSION: ${{ matrix.HYPERSPY_VERSION }}
      ROSETTASCIIO_VERSION: ${{ matrix.ROSETTASCIIO_VERSION }}
      INSTALL_SOURCE_FROM_REPOSITORY: false
      DEPENDENCIES_DEV: ${{ matrix.DEPENDENCIES_DEV }}
      DEPENDENCIES_PRE_RELEASE: ${{ matrix.DEPENDENCIES_PRE_RELEASE }}
      USE_CONDA: ${{ matrix.USE_CONDA }}
