name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 0 * * *'
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  integration_test:
    name: rs_${{ matrix.ROSETTASCIIO_VERSION }} hs_${{ matrix.HYPERSPY_VERSION }} ext_${{ matrix.EXTENSION_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        LABEL: ['']
        ROSETTASCIIO_VERSION: [release, dev]
        HYPERSPY_VERSION: [release, RnM, RnP]
        EXTENSION_VERSION: [release, dev]
        DEPENDENCIES_DEV: ['']
        DEPENDENCIES_PRE_RELEASE: ['']
        NUMBA_DEV: [false]
        USE_CONDA: [false]
        ADDITIONAL_PACKAGES: ['']
        PLATFORM: [ubuntu-latest]
        include:
          - LABEL: Conda OpenBLAS
            ROSETTASCIIO_VERSION: release
            HYPERSPY_VERSION: release
            EXTENSION_VERSION: release
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: false
            USE_CONDA: true
            ADDITIONAL_PACKAGES: 'libblas=*=*openblas'
            PLATFORM: ubuntu-latest
          - LABEL: Conda OpenBLAS
            ROSETTASCIIO_VERSION: release
            HYPERSPY_VERSION: release
            EXTENSION_VERSION: release
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: false
            USE_CONDA: true
            ADDITIONAL_PACKAGES: 'libblas=*=*openblas'
            PLATFORM: windows-latest
          - LABEL: Conda MKL
            ROSETTASCIIO_VERSION: release
            HYPERSPY_VERSION: release
            EXTENSION_VERSION: release
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: false
            USE_CONDA: true
            ADDITIONAL_PACKAGES: 'libblas=*=*mkl'
            PLATFORM: ubuntu-latest
          - LABEL: Conda MKL
            ROSETTASCIIO_VERSION: release
            HYPERSPY_VERSION: release
            EXTENSION_VERSION: release
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: false
            USE_CONDA: true
            ADDITIONAL_PACKAGES: 'libblas=*=*mkl'
            PLATFORM: windows-latest
          - LABEL: Dependencies dev
            ROSETTASCIIO_VERSION: dev
            HYPERSPY_VERSION: RnM
            EXTENSION_VERSION: dev
            # testing against numba dev is done in a separate job
            DEPENDENCIES_DEV: matplotlib scipy scikit-learn sympy h5py scikit-image
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: false
            USE_CONDA: false
            ADDITIONAL_PACKAGES: ''
            PLATFORM: ubuntu-latest
          - LABEL: Dependencies pre_release
            ROSETTASCIIO_VERSION: dev
            HYPERSPY_VERSION: RnM
            EXTENSION_VERSION: dev
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: matplotlib scipy scikit-learn sympy h5py scikit-image numba
            NUMBA_DEV: false
            USE_CONDA: false
            ADDITIONAL_PACKAGES: ''
            PLATFORM: ubuntu-latest
          - LABEL: Numba dev
            ROSETTASCIIO_VERSION: dev
            HYPERSPY_VERSION: RnM
            EXTENSION_VERSION: dev
            DEPENDENCIES_DEV: ''
            DEPENDENCIES_PRE_RELEASE: ''
            NUMBA_DEV: true
            USE_CONDA: false
            ADDITIONAL_PACKAGES: ''
            PLATFORM: ubuntu-latest

    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/integration_tests.yml@main
    with:
      # don't run etspy until test suite is fixed
      # EXTENSIONS: 'hyperspy-gui-ipywidgets hyperspy-gui-traitsui exspy holospy lumispy pyxem atomap etspy'
      EXTENSIONS: 'hyperspy-gui-ipywidgets hyperspy-gui-traitsui exspy holospy lumispy pyxem kikuchipy atomap'
      PIP_EXTRAS: '[all,tests]'
      INSTALL_SOURCE_FROM_REPOSITORY: false
      ROSETTASCIIO_VERSION: ${{ matrix.ROSETTASCIIO_VERSION }}
      HYPERSPY_VERSION: ${{ matrix.HYPERSPY_VERSION }}
      EXTENSION_VERSION: ${{ matrix.EXTENSION_VERSION }}
      DEPENDENCIES_DEV: ${{ matrix.DEPENDENCIES_DEV }}
      DEPENDENCIES_PRE_RELEASE: ${{ matrix.DEPENDENCIES_PRE_RELEASE }}
      NUMBA_DEV: ${{ matrix.NUMBA_DEV }}
      USE_CONDA: ${{ matrix.USE_CONDA }}
      LABEL: ${{ matrix.LABEL }}
      ADDITIONAL_PACKAGES: ${{ matrix.ADDITIONAL_PACKAGES }}
      PLATFORM: ${{ matrix.PLATFORM }}
