name: Update README.md

on:
  workflow_dispatch:
    workflow: "*"
  schedule:
    - cron:  '0 0 * * 6'
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@master
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          # use base environment, so that when using pip, this is from the
          # mambaforge distribution
          auto-activate-base: true
          activate-environment: ""

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Install extensions
        run: |
          mamba install --file extension_list.txt

      - name: Conda list
        run: |
          conda list

      - name: Update README.md
        run: |
          python make_README.py

      - name: Push changes to Github
        run: |
          git config --global user.name "Automatic README update"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update README.md"
          git push
